### ISSUE TITLE
fix CI build

### ISSUE THREAD

**Issue by auvipy** [scls19fr/openweathermap_requests#2]

**Comment by scls19fr** [comment]
You are free to provide a PR.

**Comment by scls19fr** [comment]
See http://openweathermap.org/history

Historical data grouped by hours
Weather station data grouped by hours

Example http://api.openweathermap.org/data/2.5/history/station?id=5091&type=hour

This is also broken

So it doesn't seem to be a problem of my project.

**Comment by scls19fr** [comment]
See also
http://api.openweathermap.org/data/2.5/history/city?lat=41.85&lon=-87.65
it raises `500 /proxy/data/2.5/history/city?lat=41.85&lon=-87.65&`

I can't help

**Comment by scls19fr** [comment]
https://travis-ci.org/scls19fr/openweathermap_requests/builds/76601239 passed
